<a href="https://colab.research.google.com/github/SARA3SAEED/ML-Mu/blob/main/s05a_supervised_classification_model_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Supervised Learning | Classification (Model Selection & Evaluation)

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# sns.set()

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


==========

## Model Selection & Evaluation

### Model Selection

In [ ]:
# from IPython.display import Image
# Image("imgs/ml_map.png")

Choosing the Right Estimator: https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

### Importing Dataset

In [4]:
df = pd.read_csv('/content/drive/MyDrive/ML-Mu/supervised-classification/datasets/heights_weights.csv')
df

Height      Weight  Male
0     73.847017  241.893563     1
1     68.781904  162.310473     1
2     74.110105  212.740856     1
3     71.730978  220.042470     1
4     69.881796  206.349801     1
...         ...         ...   ...
9995  66.172652  136.777454     0
9996  67.067155  170.867906     0
9997  63.867992  128.475319     0
9998  69.034243  163.852461     0
9999  61.944246  113.649103     0

[10000 rows x 3 columns]

### Exploring Data

In [5]:
sns.scatterplot(x="Height", y="Weight", hue="Male", data=df)

<Axes: xlabel='Height', ylabel='Weight'>

### Splitting & Preprocessing Data

In [6]:
X = df.iloc[:,0:2].values
X

array([[ 73.84701702, 241.89356318],
       [ 68.78190405, 162.31047252],
       [ 74.11010539, 212.74085556],
       ...,
       [ 63.86799221, 128.47531878],
       [ 69.03424313, 163.85246135],
       [ 61.94424588, 113.64910268]])

In [7]:
y = df.iloc[:,2].values
y

array([1, 1, 1, ..., 0, 0, 0])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
X_train.shape

(7000, 2)

In [10]:
X_test.shape

(3000, 2)

In [11]:
Y_train.shape

(7000,)

In [12]:
Y_test.shape

(3000,)

### Model Selection & Evaluation

Scikit-learn Classification Metrics: https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics

In [16]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


### 1] Logestic Regression Performance

In [17]:
from sklearn.linear_model import LogisticRegression

# Fit (train) the Logistic Regression classifier
logreg_clf = LogisticRegression()
logreg_model = logreg_clf.fit(X_train, Y_train)
logreg_prediction = logreg_clf.predict(X_test)

In [18]:
print("Accuracy {0:.2f}%".format(100*accuracy_score(logreg_prediction, Y_test)))

Accuracy 91.87%


In [19]:
print(confusion_matrix(logreg_prediction, Y_test))

[[1385  140]
 [ 104 1371]]


In [20]:
# plot_confusion_matrix(logreg_clf, X_test, Y_test)

NameError: name 'plot_confusion_matrix' is not defined

In [21]:
print(classification_report(logreg_prediction, Y_test))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      1525
           1       0.91      0.93      0.92      1475

    accuracy                           0.92      3000
   macro avg       0.92      0.92      0.92      3000
weighted avg       0.92      0.92      0.92      3000



### 2] Random Forest Performance

In [25]:
from sklearn.ensemble import RandomForestClassifier

# Fit (train) the Random Forest classifier
ranfor_clf = RandomForestClassifier()
ranfor_model = ranfor_clf.fit(X_train, Y_train)
ranfor_prediction = ranfor_clf.predict(X_test)

In [26]:
print("Accuracy {0:.2f}%".format(100*accuracy_score(ranfor_prediction, Y_test)))

Accuracy 90.20%


In [27]:
print(confusion_matrix(ranfor_prediction, Y_test))

[[1375  180]
 [ 114 1331]]


In [28]:
# plot_confusion_matrix(ranfor_clf, X_test, Y_test)

In [29]:
print(classification_report(ranfor_prediction, Y_test))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90      1555
           1       0.88      0.92      0.90      1445

    accuracy                           0.90      3000
   macro avg       0.90      0.90      0.90      3000
weighted avg       0.90      0.90      0.90      3000



### 3] Support Vector Machine Performance

In [30]:
from sklearn.svm import SVC

# Fit (train) the Support Vector Machine classifier
svm_clf = SVC()
svm_model = svm_clf.fit(X_train, Y_train)
svm_prediction = svm_clf.predict(X_test)

In [31]:
print("Accuracy {0:.2f}%".format(100*accuracy_score(svm_prediction, Y_test)))

Accuracy 91.40%


In [32]:
print(confusion_matrix(svm_prediction, Y_test))

[[1382  151]
 [ 107 1360]]


In [33]:
# plot_confusion_matrix(svm_clf, X_test, Y_test)

In [34]:
print(classification_report(svm_prediction, Y_test))

              precision    recall  f1-score   support

           0       0.93      0.90      0.91      1533
           1       0.90      0.93      0.91      1467

    accuracy                           0.91      3000
   macro avg       0.91      0.91      0.91      3000
weighted avg       0.91      0.91      0.91      3000



### 4] K-NN Classifier Performance

In [35]:
from sklearn.neighbors import KNeighborsClassifier

# Fit (train) the KNN classifier
knn_clf = KNeighborsClassifier()
knn_model = knn_clf.fit(X_train, Y_train)
knn_prediction = knn_clf.predict(X_test)

In [36]:
print("Accuracy {0:.2f}%".format(100*accuracy_score(knn_prediction, Y_test)))

Accuracy 90.27%


In [37]:
print(confusion_matrix(knn_prediction, Y_test))

[[1367  170]
 [ 122 1341]]


In [38]:
# plot_confusion_matrix(knn_clf, X_test, Y_test)

In [39]:
print(classification_report(knn_prediction, Y_test))

              precision    recall  f1-score   support

           0       0.92      0.89      0.90      1537
           1       0.89      0.92      0.90      1463

    accuracy                           0.90      3000
   macro avg       0.90      0.90      0.90      3000
weighted avg       0.90      0.90      0.90      3000



### Other Evaluation Metrics

In [40]:
from sklearn.metrics import plot_roc_curve

ImportError: cannot import name 'plot_roc_curve' from 'sklearn.metrics' (/usr/local/lib/python3.10/dist-packages/sklearn/metrics/__init__.py)

##### Logistic Regression

In [ ]:
plot_roc_curve(logreg_model,X_test,Y_test)

##### Random Forest

In [ ]:
plot_roc_curve(ranfor_model,X_test,Y_test)

##### Support Vector Machine

In [ ]:
plot_roc_curve(svm_model,X_test,Y_test)

##### K-NN Classifier

In [ ]:
plot_roc_curve(knn_model,X_test,Y_test)

==========

# THANK YOU!